export const CHANGE_SHARE_ONE = 'CHANGE_SHARE_ONE';
export const CHANGE_SHARE_TWO = 'CHANGE_SHARE_TWO';
export const CHANGE_SHARE_THREE = 'CHANGE_SHARE_THREE';
export const CHANGE_SHARE_FOUR = 'CHANGE_SHARE_FOUR';

